#frontend/Dockerfile
FROM openjdk:17-jdk-slim

WORKDIR /app

# Copy built JAR from Jenkins server
COPY target/app*.jar application-0.0.1-SNAPSHOT.jar

# Expose Spring Boot port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "application-0.0.1-SNAPSHOT.jar"]

